/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Tue Jan  1 20:52:13 2019. */

#include "screen.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ScreenCommand_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t ScreenStatus_fields[2] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, ScreenStatus, status, status, 0),
    PB_LAST_FIELD
};

const pb_field_t ScreenGranted_fields[2] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, ScreenGranted, message, message, 0),
    PB_LAST_FIELD
};




/* @@protoc_insertion_point(eof) */
