/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 at Tue Jan  1 20:52:13 2019. */

#ifndef PB_SCREEN_PB_H_INCLUDED
#define PB_SCREEN_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _ScreenCommand_CommandType {
    ScreenCommand_CommandType_NONE = 0,
    ScreenCommand_CommandType_STATUS = 4,
    ScreenCommand_CommandType_GRANT = 5
} ScreenCommand_CommandType;
#define _ScreenCommand_CommandType_MIN ScreenCommand_CommandType_NONE
#define _ScreenCommand_CommandType_MAX ScreenCommand_CommandType_GRANT
#define _ScreenCommand_CommandType_ARRAYSIZE ((ScreenCommand_CommandType)(ScreenCommand_CommandType_GRANT+1))

typedef enum _ScreenStatus_Status {
    ScreenStatus_Status_IDLE = 0,
    ScreenStatus_Status_DENIED = 1,
    ScreenStatus_Status_LOADING = 3
} ScreenStatus_Status;
#define _ScreenStatus_Status_MIN ScreenStatus_Status_IDLE
#define _ScreenStatus_Status_MAX ScreenStatus_Status_LOADING
#define _ScreenStatus_Status_ARRAYSIZE ((ScreenStatus_Status)(ScreenStatus_Status_LOADING+1))

/* Struct definitions */
typedef struct _ScreenCommand {
    char dummy_field;
/* @@protoc_insertion_point(struct:ScreenCommand) */
} ScreenCommand;

typedef struct _ScreenGranted {
    pb_callback_t message;
/* @@protoc_insertion_point(struct:ScreenGranted) */
} ScreenGranted;

typedef struct _ScreenStatus {
    ScreenStatus_Status status;
/* @@protoc_insertion_point(struct:ScreenStatus) */
} ScreenStatus;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ScreenCommand_init_default               {0}
#define ScreenStatus_init_default                {_ScreenStatus_Status_MIN}
#define ScreenGranted_init_default               {{{NULL}, NULL}}
#define ScreenCommand_init_zero                  {0}
#define ScreenStatus_init_zero                   {_ScreenStatus_Status_MIN}
#define ScreenGranted_init_zero                  {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define ScreenGranted_message_tag                1
#define ScreenStatus_status_tag                  1

/* Struct field encoding specification for nanopb */
extern const pb_field_t ScreenCommand_fields[1];
extern const pb_field_t ScreenStatus_fields[2];
extern const pb_field_t ScreenGranted_fields[2];

/* Maximum encoded size of messages (where known) */
#define ScreenCommand_size                       0
#define ScreenStatus_size                        2
/* ScreenGranted_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SCREEN_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
